# real time modified fine-tune config
shot:
  res: 5e-3
  receptive_field: 10 # no need when normal_channel=False
pointnet:
  normal_channel: True
  state: False



cache: True
joints: 1
types: ['revolute'] # length should be equal to joints, even though encoder.state is False, order should match
states: [0]         # length should be equal to joints, even though encoder.state is False, order should match
sample_points: 4096
test_sample_points: 4096
point_dropout_ratio: 0.875
point_dropout_prob: 0.5
point_scale_low: 0.8
point_scale_high: 1.25
point_shift_range: 0.1
lambda_axis: 2
lambda_state: 0

weight_path: ./weights/04-20-21-34
dataset:
  dataset_path: ../../articulation-generation/logs/L515_test
  train_instances: [
    'without_train'
  ]
  test_instances: [
    'without_test'
  ]
device: 0
num_workers: 8
batch_size: 64
max_epoch: 200
lr: 1e-4
weight_decay: 1e-4

hydra:
  run:
    dir: ./weights/${now:%m-%d-%H-%M}
