# final microwave config
dataset:
  # dataset_path: ../articulation-generation/logs/Microwave_v3
  dataset_path: /data2/junbo/Microwave_v3
  train_instances: [
    '7119',
    '7128',
    '7167',
    '7221',
    '7236',
    '7263',
    '7265',
    '7296',
  ]
  test_instances: [
    '7304',
    '7310',
    '7349',
    '7366'
  ]
shot:
  res: 5e-3
  receptive_field: 10
shot_encoder:
  hidden_dims: [128, 128, 128, 128, 128]
  feature_dim: 64
  bn: False
  ln: False   # bn and ln can only be set one
  dropout: 0
encoder:
  hidden_dims: [128, 128, 128, 128, 128]
  rot_num_bins: 36
  state: False
  bn: False
  ln: False   # bn and ln can only be set one
  dropout: 0

device: 1
num_workers: 8
batch_size: 1
max_epoch: 100
lr: 1e-3
weight_decay: 0
step: 15      # 0 means CosineAnnealingLR
warmup: False

cache: True
joints: 1
types: ['revolute'] # length should be equal to joints, even though encoder.state is False, order should match
states: [0]         # length should be equal to joints, even though encoder.state is False, order should match, in degree or cm
samples: 4096
test_samples: 4096
sample_points: 100000
test_sample_points: 100000
num_more: 3
topk: 0.5
goodness: both
lambda_axis: 0.1
lambda_state: 0
lambda_conf: 0.5

hydra:
  run:
    dir: ./weights/${now:%m-%d-%H-%M}
