# final drawer config
dataset:
  dataset_path: /data2/junbo/Drawer
  train_instances: [
    '20411',
    '23511',
    '24931',
    '26806',
    '28668'
  ]
  test_instances: [
    '24644',
    '26503'
  ]
shot:
  res: 5e-3
  receptive_field: 10 # no need when normal_channel=False
pointnet:
  normal_channel: True
  state: False

device: 0
num_workers: 8
batch_size: 64
max_epoch: 100
lr: 1e-2
weight_decay: 1e-4

cache: True
joints: 1
types: ['prismatic'] # length should be equal to joints, even though encoder.state is False, order should match
states: [0]         # length should be equal to joints, even though encoder.state is False, order should match, in degree or cm
sample_points: 4096
test_sample_points: 4096
point_dropout_ratio: 0.875
point_dropout_prob: 0.5
point_scale_low: 0.8
point_scale_high: 1.25
point_shift_range: 0.1
lambda_axis: 2
lambda_state: 0

hydra:
  run:
    dir: ./weights/${now:%m-%d-%H-%M}
