# final microwave config
dataset:
  # dataset_path: ../articulation-generation/logs/Microwave_v4
  dataset_path: /data2/junbo/Microwave_v4
  train_instances: [
    '7119',
    '7128',
    '7167',
    '7221',
    '7236',
    '7263',
    '7265',
    '7296',
  ]
  test_instances: [
    '7304',
    '7310',
    '7349',
    '7366'
  ]
point_encoder:
  normal_channel: False
  feature_dim: 256  # best <= 256
grasp_encoder:
  grasp_dim: 16     # fixed
  hidden_dims: [32, 64]
  feature_dim: 128
  bn: False
  ln: True
  dropout: 0
joint_encoder:
  state_channel: False
  hidden_dims: [16, 32]
  feature_dim: 64
  bn: False
  ln: True
  dropout: 0
embedding_net:
  hidden_dims: [512, 256]
  bn: False
  ln: True
  dropout: 0
  classification: True
  # such as [[[-1], 0.0, [0.0, 0.167]], [[0], 0.333, [0.167, 0.5]], [[1], 0.667, [0.5, 0.833]], [[2], 1.0, [0.833, 1.0]]]
  # or [[[-1, 0], 0.0, [0.0, 0.333]], [[1], 0.5, [0.333, 0.667]], [[2], 1.0, [0.667, 1.0]]]
  # or [[[-1], 0.0, [0.0, 0.333]], [[0], 0.5, [0.333, 0.667]], [[1, 2], 1.0, [0.667, 1.0]]]
  # or [[[0], 0.0, [0.0, 0.333]], [[1], 0.5, [0.333, 0.667]], [[2], 1.0, [0.667, 1.0]]]
  # or [[[-1, 0], 0.0, [0.0, 0.5]], [[1, 2], 1.0, [0.5, 1.0]]]
  # or [[[0], 0.0, [0.0, 0.5]], [[1, 2], 1.0, [0.5, 1.0]]]
  levels: [[[-1, 0], 0.0, [0.0, 0.5]], [[1, 2], 1.0, [0.5, 1.0]]]

shot:
  res: 5e-3
  receptive_field: 10
cache: True

device: 0
num_workers: 8
batch_size: 64
max_epoch: 100
lr: 5e-4
weight_decay: 0
normalization: True
augmentation: True
point_dropout_ratio: 0.875  # not used when augmentation set to False
point_dropout_prob: 0.5     # not used when augmentation set to False
point_scale_low: 0.8        # not used when augmentation set to False
point_scale_high: 1.25      # not used when augmentation set to False
point_shift_range: 0.1      # not used when augmentation set to False

seed: 42
samples: 4096
test_samples: 4096
joints: 1
types: ['revolute'] # length should be equal to joints, order should match
states: [90]        # length should be equal to joints, order should match, in degree or cm

hydra:
  run:
    dir: ./weights/${now:%m-%d-%H-%M}
